# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/p6nyqsw5qbg114gprcj4ci8j4nx9nhnb-cmake-3.26.4/bin/cmake

# The command to remove a file.
RM = /nix/store/p6nyqsw5qbg114gprcj4ci8j4nx9nhnb-cmake-3.26.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jason/projects/C-MemoryMuncher

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jason/projects/C-MemoryMuncher

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/nix/store/p6nyqsw5qbg114gprcj4ci8j4nx9nhnb-cmake-3.26.4/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/nix/store/p6nyqsw5qbg114gprcj4ci8j4nx9nhnb-cmake-3.26.4/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/nix/store/p6nyqsw5qbg114gprcj4ci8j4nx9nhnb-cmake-3.26.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jason/projects/C-MemoryMuncher/CMakeFiles /home/jason/projects/C-MemoryMuncher//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jason/projects/C-MemoryMuncher/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MemoryMuncher

# Build rule for target.
MemoryMuncher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MemoryMuncher
.PHONY : MemoryMuncher

# fast build rule for target.
MemoryMuncher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemoryMuncher.dir/build.make CMakeFiles/MemoryMuncher.dir/build
.PHONY : MemoryMuncher/fast

#=============================================================================
# Target rules for targets named standard_malloc

# Build rule for target.
standard_malloc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 standard_malloc
.PHONY : standard_malloc

# fast build rule for target.
standard_malloc/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/standard_malloc.dir/build.make tests/CMakeFiles/standard_malloc.dir/build
.PHONY : standard_malloc/fast

#=============================================================================
# Target rules for targets named munch_functionality

# Build rule for target.
munch_functionality: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 munch_functionality
.PHONY : munch_functionality

# fast build rule for target.
munch_functionality/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/munch_functionality.dir/build.make tests/CMakeFiles/munch_functionality.dir/build
.PHONY : munch_functionality/fast

#=============================================================================
# Target rules for targets named munch_heap_test

# Build rule for target.
munch_heap_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 munch_heap_test
.PHONY : munch_heap_test

# fast build rule for target.
munch_heap_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/munch_heap_test.dir/build.make tests/CMakeFiles/munch_heap_test.dir/build
.PHONY : munch_heap_test/fast

#=============================================================================
# Target rules for targets named malloc_heap_test

# Build rule for target.
malloc_heap_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 malloc_heap_test
.PHONY : malloc_heap_test

# fast build rule for target.
malloc_heap_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/malloc_heap_test.dir/build.make tests/CMakeFiles/malloc_heap_test.dir/build
.PHONY : malloc_heap_test/fast

muncher.o: muncher.c.o
.PHONY : muncher.o

# target to build an object file
muncher.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemoryMuncher.dir/build.make CMakeFiles/MemoryMuncher.dir/muncher.c.o
.PHONY : muncher.c.o

muncher.i: muncher.c.i
.PHONY : muncher.i

# target to preprocess a source file
muncher.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemoryMuncher.dir/build.make CMakeFiles/MemoryMuncher.dir/muncher.c.i
.PHONY : muncher.c.i

muncher.s: muncher.c.s
.PHONY : muncher.s

# target to generate assembly for a file
muncher.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemoryMuncher.dir/build.make CMakeFiles/MemoryMuncher.dir/muncher.c.s
.PHONY : muncher.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... MemoryMuncher"
	@echo "... malloc_heap_test"
	@echo "... munch_functionality"
	@echo "... munch_heap_test"
	@echo "... standard_malloc"
	@echo "... muncher.o"
	@echo "... muncher.i"
	@echo "... muncher.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

